FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

# Create a non-root user
RUN useradd -ms /bin/bash appuser
USER appuser

CMD ["python", "app.py"]